[package]
name = "smpi-sm-provider"
version = "0.0.1"
edition = "2021"

[dependencies]
smpi-base = { path = "../smpi-base" }
smpi-runtime = { path = "../smpi-runtime" }
futures = { version = "0.3.30", features = ["executor"] }
