[package]
name = "smpi-ucx-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
smpi-ucx-sys = { path = "../smpi-ucx-sys" }
nix = "0.26.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
log = "0.4.17"
env_logger = "0.10.0"
